to_tensor should expects a numpy array
Fixes error:

```
RuntimeError: tried to construct a tensor from a float sequence, but found an item of type numpy.int64 at index (1)
```